name: Test New Workflow
on:
  push:
    branches:
      - main
jobs:
  environment:
    name: Prepare Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
          with: version: 9.4.0

      - name: Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            package.json
            web/package.json
            api/package.json
        - run: pnpm i

  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    needs: environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Checks
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

        - name: Type Check Web
          run: pnpm web:type

        - name: Type Check API
          run: pnpm api:type

        - name: Lint
          run:  pnpm lint

        - name: Format
          run: pnpm format

  testing:
    name: Testing
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses actions/checkout@v4

      - name: Run Jest Tests
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          run: pnpm test

      - name: Prepare Web Build
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          run: pnpm web:build

      - name: Save Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          if-no-files-found: error
          path: web

      - name: Prepare API Build
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          run: pnpm api:build

      - name: Save Web Build
        needs: Prepare API Build
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          if-no-files-found: error
          path: api

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          build: pnpm cypress info
          start: pnpm web:start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 30
          browser: chrome
          record: true
          parallels: true
          group: 'UI - Chrome'
          spec: cypress/tests/e2e
          config-file: config/cypress.config.mjs

  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Web Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/project-starter-web:latest .web
          docker push ${{ secrets.DOCKER_USERNAME }}/project-starter-web:latest

      - name: Build and Push API Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/project-starter-api:latest ./api
          docker push ${{ secrets.DOCKER_USERNAME }}/project-starter-api:latest
